import "./globals.css";

export const metadata = {
  title: "2nd page",
  description: "Generated by create next app",
};

export default function SecondaryLayout({ children }) {

  return (
    children
  );
}
